#!/bin/bash

#checkout hook to locally set user name and email based on user defined patterns
#The patterns are matched against the clone url.
#
#Based on http://www.dvratil.cz/2015/12/git-trick-628-automatically-set-commit-author-based-on-repo-url/

function warn {
  echo -e "\n$1 Email and author not initialized!"
  echo -e "You can define them manually in the local config or run\n\n    git config --local user.disable true\n\nto get rid of this warning."
}

email="$(git config --local user.email)"
name="$(git config --local user.name)"
disable="$(git config --local user.disable)"

if [[ -n $email || -n $name || $disable == "true" ]]; then
  exit 0
fi

#get remote name:
#  only one: take it
#  more: take "origin", or fail
remote="$([[ $(git remote | wc -l) -eq 1 ]] && git remote || git remote | grep "^origin$")"

if [[ -z $remote ]]; then
  warn "Failed to detect remote."
  exit 0
fi

url="$(git config --local remote.${remote}.url)"

if [[ ! -f ~/.git-clone-init ]]; then
cat << INPUT > ~/.git-clone-init
#!/bin/bash

case "\$url" in
  *@github.com:*    ) email=""; name="";;
  *//github.com/*   ) email=""; name="";;
esac
INPUT
  echo -e "\nMissing file ~/.git-clone-init. Template created..."
  echo -e "Edit this file and run \n\n    git checkout\n\nfrom within the cloned repository."
  exit 0
fi
. ~/.git-clone-init

if [[ -z $name || -z $email ]]; then
  warn "Failed to detect identity using ~/.git-clone-init."
  exit 0
fi

git config --local user.email "$email"
git config --local user.name "$name"

echo "Identitiy set to $name <$email>"
